version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - kind/dependency
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: nuget
    directory: /ProjectSBS
    schedule:
      interval: weekly
    labels:
      - kind/dependency
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
