global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Recurrents.DataContracts;
global using Recurrents.DataContracts.Serialization;
global using Recurrents.Models;
global using Recurrents.Presentation;
global using Recurrents.Services.Caching;
global using Recurrents.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
